Linked Open Data in Forestry
==============================

Guillermo Vega-Gorgojo


1. Linked Open Data
2. Semantic Data and Ontologies
3. Consuming Linked Open Data
4. Linked Open Data in Forestry

### Semantic Web
The Semantic Web is an extension of the World Wide Web through standards by the World Wide Web Consortium. The standards promote common data formats and exchange protocols on the Web, most fundamentally the Resource Description Framework. 

### Linked Data
In computing, linked data is a method of publishing structured data so that it can be interlinked and become more useful through semantic queries. It builds upon standard Web technologies such as HTTP, RDF and URIs, but rather than using them to serve web pages for human readers, it extends them to share information in a way that can be read automatically by computers. 


### What is RDF
RDF, the Resource Description Framework, is one of the key ingredients of Linked Data, and provides a generic 
graph-based data model for describing things, including their relationships with other things. RDF data can be written 
down in a number of different ways, known as serialisations. Examples of RDF serialisations include RDF/XML, Notation-3 
(N3), Turtle, N-Triples, RDFa, and RDF/JSON.

### SPARQL
SPARQL is an RDF query language, that is, a semantic query language for databases, able to retrieve and manipulate data stored in Resource Description Framework format. It was made a standard by the RDF Data Access Working Group of the World Wide Web Consortium, and is recognized as one of the key technologies of the semantic web.

### DBpedia
DBpedia is a project aiming to extract structured content from the information created in the Wikipedia project. This structured information is made available on the World Wide Web. DBpedia allows users to semantically query relationships and properties of Wikipedia resources, including links to other related datasets. Tim Berners-Lee described DBpedia as one of the most famous parts of the decentralized Linked Data effort.

### wikidata
Info: www.wikidata.org


### Four Principles for Publishing LinkedOpen Data
* Berners Lee 2006


A relation between two resources
Subject-Predicate-Object

``dbr:Pinus_nigra rdfs:label "pinus nigra"``


###  RDF Graph

Can be visualized as a node and directed-arc diagram

* ``dbr:Pinus_nigra rdfs:label "Pinus nigra"``


### Turtle

Terse RDF Triple Language (Turtle) is a syntax and file format for expressing data in the Resource Description Framework (RDF) data model. Turtle syntax is similar to that of SPARQL, an RDF query language. 
RDF represents information using semantic triples, which comprise a subject, predicate, and object. Each item in the triple is expressed as a Web URI. Turtle provides a way to group three URIs to make a triple, and provides ways to abbreviate such information, for example by factoring out common portions of URIs. For example: 
 <http://example.org/person/Mark_Twain>
    <http://example.org/relation/author>
    <http://example.org/books/Huckleberry_Finn> .

### Ontology
An Ontology is a shared conceptualization of a domain.
It is used to make sense of unorganized information, and manages commonality and variability.

### Web Ontology Language (OWL)
The Web Ontology Language (OWL) is a family of knowledge representation languages for authoring ontologies. Ontologies are a formal way to describe taxonomies and classification networks, essentially defining the structure of knowledge for various domains: the nouns representing classes of objects and the verbs representing relations between the objects. Ontologies resemble class hierarchies in object-oriented programming but there are several critical differences. Class hierarchies are meant to represent structures used in source code that evolve fairly slowly (typically monthly revisions) whereas ontologies are meant to represent information on the Internet and are expected to be evolving almost constantly. 

