
Remotely Piloted Aircraft Systems (RPAS) 
=================================================
José Martínez Rubio

Company: Geobit

#### Drones

* DroidWorks VM X4
* Mikrokopter MK8 Hexacopter
* DJI Phnatom 4 - Advanced

#### Pros and Cons of RPAS

* less reliability
* Lower Bad Weather Conditions
* Worse Quality of on-board sensors

* Discrete
* Easy Deployment
* Low Altitude Flight
* Low Risk for Humans
 
### Forest Analysis
* Combined operation with TLS


#### Ground Sample Distance (GSD)
In remote sensing, ground sample distance (GSD) in a digital photo (such as an orthophoto) of the ground from air or space is the distance between pixel centers measured on the ground. For example, in an image with a one-meter GSD, adjacent pixels image locations are 1 meter apart on the ground. GSD is a measure of one limitation to image resolution, that is, the limitation due to sampling.
GSD is also referred to as ground-projected sample interval (GSI) or ground-projected instantaneous field of view (GIFOV).


#### Mission Planning
* GSD
* Altitude AGL
* Front Side Overlap
* Flight Pattern and Orientation
* Boundaries and Void Areas
* Follow Terrain
* VLOS BVLOS (Visual Line of Sight v Beyond Visual Line of Sight) Regulation on Drone Piloting


### GCPs: Ground Control Points

Ground Control Points, or GCPs, are marked points on the ground that have a known geographic location. In aerial surveying, a drone can be used to autonomously collect photos of the survey area. If used, GCPs must be visible in these aerial photos. The photos are then processed in the cloud using drone mapping software.


GeoReference

### 3D data production
* Textured Models
* Ortho Images
* RGB Dense Cloud (unclassified)
* 2.5D surface model out of dense point cloud

Semi-Automated Tree Height Extraction
