### Using custom functions
By default, the statistics generated by sp_summarise for each attribute will be its mean, median, standard deviation, minimum and maximum. However, by using the statFuns argument, custom functions can be used instead.

Any custom function should observe the following conditions:
* It should accept numeric vectors.
* It should handle NA values.
* It should have a single argument followed by an ellipsis (three dots). i.e.: function(x, ...)
* It should return a single numeric value.

For instance, the following function will calculate the 98th quantile of a numeric vector.
quant98 <- function(x, ...) quantile(x, c(.98), na.rm = TRUE)
To have this function applied using sp_summarise, it must be put into a named list. Naming the functions in the list is needed for labelling the function’s outputs.
```{r}
# Create list of functions
custFuns <- list(quant98, max)
names(custFuns) <- c("98thQuantile", "Max")

# Generate statistics for crown areas and tree heights
sp_summarise(crownsPoly, variables = c("crownArea", "height"), statFuns = custFuns)
##                            Value
## TreeCount             1077.00000
## crownArea98thQuantile   20.87000
## crownAreaMax            53.00000
## height98thQuantile      11.57175
## heightMax               13.49121
```
